@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jun 30 00:31:17 +0530 2026
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_im2col_behav -key {Behavioral:sim_1:Functional:tb_im2col} -tclbatch tb_im2col.tcl -protoinst "protoinst_files/bd_919a.protoinst" -protoinst "protoinst_files/system.protoinst" -log simulate.log"
call xsim  tb_im2col_behav -key {Behavioral:sim_1:Functional:tb_im2col} -tclbatch tb_im2col.tcl -protoinst "protoinst_files/bd_919a.protoinst" -protoinst "protoinst_files/system.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
