# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Yash/KGP/hardware_project/vivado_ws/increment_core/increment_core.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
# IP: The module: 'system_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Yash/KGP/hardware_project/vivado_ws/increment_core/increment_core.gen/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Yash/KGP/hardware_project/vivado_ws/increment_core/increment_core.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
# IP: The module: 'system_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Yash/KGP/hardware_project/vivado_ws/increment_core/increment_core.gen/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
